"use client";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { useEffectiveAcademicPeriodId } from "@/features/academic-periods";
import { useAcademicPlans } from "@/features/planning/hooks/use-academic-plans";
import type { AcademicPlansFilters } from "@/features/planning/types";
import { canManageAcademicPlanning,canViewAcademicPlanning } from "@/lib/permissions";
import { useAuthStore } from "@/stores/use-auth-store";
const defaults:AcademicPlansFilters={page:1,limit:10};
export function AcademicPlansPage(){const user=useAuthStore(s=>s.user);const effectivePeriod=useEffectiveAcademicPeriodId();const [filters,setFilters]=useState<AcademicPlansFilters>(defaults);const query=useAcademicPlans({...filters,academicPeriodId:filters.academicPeriodId??effectivePeriod});if(!canViewAcademicPlanning(user?.role))return <p className="py-12 text-center text-sm text-muted-foreground">No tienes permiso para ver planificación académica.</p>;const manage=canManageAcademicPlanning(user?.role);return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Planificación académica</h1><p className="text-sm text-muted-foreground">{manage?"Crea y organiza tus planes por período académico.":"Consulta los planes académicos de la institución."}</p></div>{manage?<Button asChild><Link href="/academic-plans/new">Nuevo plan</Link></Button>:null}</div><div className="grid gap-3 rounded-lg border border-border bg-card p-4 sm:grid-cols-2 lg:grid-cols-3"><div className="space-y-1"><Label htmlFor="plan-search">Buscar</Label><Input id="plan-search" value={filters.search??""} onChange={e=>setFilters({...filters,page:1,search:e.target.value||undefined})}/></div><div className="space-y-1"><Label htmlFor="plan-status">Estado</Label><Select id="plan-status" value={filters.status??""} onChange={e=>setFilters({...filters,page:1,status:(e.target.value||undefined) as AcademicPlansFilters["status"]})}><option value="">Todos</option><option value="DRAFT">Borrador</option><option value="PUBLISHED">Publicado</option></Select></div></div>{query.isLoading?<p className="text-sm text-muted-foreground">Cargando planes…</p>:query.isError?<Card><CardContent className="p-6 text-sm text-destructive">No se pudieron cargar los planes. <Button variant="link" onClick={()=>query.refetch()}>Reintentar</Button></CardContent></Card>:query.data?.data.length?<div className="grid gap-4">{query.data.data.map(plan=><Card key={plan.id}><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{plan.title}</h2><p className="text-sm text-muted-foreground">{plan.subjectName} · {plan.courseName} {plan.courseSection}</p><p className="text-sm text-muted-foreground">{plan.academicTermName} · {plan.startDate??"Sin fechas"}{plan.endDate?` – ${plan.endDate}`:""}</p></div><div className="flex items-center gap-3"><span className="text-sm font-medium">{plan.status==="DRAFT"?"Borrador":"Publicado"}</span><Button asChild variant="outline"><Link href={`/academic-plans/${plan.id}`}>Abrir</Link></Button></div></CardContent></Card>)}</div>:<Card><CardContent className="p-8 text-center text-sm text-muted-foreground">No hay planes que coincidan con los filtros.{manage?<><br/><Button asChild className="mt-3"><Link href="/academic-plans/new">Crear primer plan</Link></Button></>:null}</CardContent></Card>}</div>}
