"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { AcademicUnitsSection } from "@/features/planning/components/academic-units-section";
import { useAcademicPlan,useDeleteAcademicPlan,usePublishAcademicPlan } from "@/features/planning/hooks/use-academic-plans";
import { canManageAcademicPlanning } from "@/lib/permissions";
import { useAuthStore } from "@/stores/use-auth-store";
export function AcademicPlanDetailPage({id}:{id:string}){const user=useAuthStore(s=>s.user);const query=useAcademicPlan(id);const publish=usePublishAcademicPlan();const remove=useDeleteAcademicPlan();if(query.isLoading)return <p className="text-sm text-muted-foreground">Cargando plan…</p>;if(query.isError||!query.data)return <p className="text-sm text-destructive">No se encontró el plan o no tienes acceso.</p>;const p=query.data;const draft=p.status==="DRAFT"&&p.academicPeriodStatus!=="CLOSED"&&canManageAcademicPlanning(user?.role);const action=async(kind:"publish"|"delete")=>{if(!window.confirm(kind==="publish"?"¿Publicar este plan? Después será de solo lectura.":"¿Eliminar este borrador?"))return;try{if(kind==="publish")await publish.mutateAsync(id);else await remove.mutateAsync(id);}catch{alert("No se pudo completar la acción.");}};return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{p.title}</h1><p className="text-sm text-muted-foreground">{p.subjectName} · {p.courseName} {p.courseSection} · {p.academicTermName}</p></div><div className="flex gap-2">{draft?<Button asChild variant="outline"><Link href={`/academic-plans/${id}/edit`}>Editar borrador</Link></Button>:null}{draft?<Button onClick={()=>action("publish")} disabled={publish.isPending}>Publicar</Button>:null}{draft?<Button variant="destructive" onClick={()=>action("delete")} disabled={remove.isPending}>Eliminar</Button>:null}</div></div><Card><CardContent className="grid gap-2 p-5 text-sm sm:grid-cols-2"><p><strong>Estado:</strong> {p.status==="DRAFT"?"Borrador":"Publicado"}</p><p><strong>Docente:</strong> {p.teacherFirstName} {p.teacherLastName}</p><p><strong>Período:</strong> {p.academicPeriodName}</p><p><strong>Fechas:</strong> {p.startDate??"Sin definir"}{p.endDate?` – ${p.endDate}`:""}</p></CardContent></Card><div className="grid gap-4">{[["Descripción",p.description],["Objetivos de aprendizaje",p.objectives],["Contenidos",p.contents],["Actividades",p.activities],["Recursos",p.resources],["Estrategia de evaluación",p.evaluationNotes],["Notas",p.notes]].filter(([,v])=>v).map(([title,value])=><Card key={title}><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="whitespace-pre-wrap text-sm">{value}</CardContent></Card>)}</div><AcademicUnitsSection academicPlanEndDate={p.endDate} academicPlanId={p.id} academicPlanStartDate={p.startDate} canManage={draft}/></div>}
