/* eslint-disable @typescript-eslint/only-throw-error -- configuration integrity failures are deliberate startup/test errors. */
import { Role } from '@prisma/client';
import {
  ALL_PERMISSIONS,
  PERMISSIONS,
  type Permission,
} from './permission-catalog';

export type RolePermissionMap = Readonly<Record<Role, readonly Permission[]>>;

const PLATFORM_CONFIGURATION_PERMISSIONS = [
  ...Object.values(PERMISSIONS.INSTITUTIONS),
  ...Object.values(PERMISSIONS.USERS),
  ...Object.values(PERMISSIONS.INSTITUTION_MEMBERSHIPS),
  ...Object.values(PERMISSIONS.ACADEMIC_PERIODS),
  ...Object.values(PERMISSIONS.ACADEMIC_LEVELS),
  ...Object.values(PERMISSIONS.GRADE_LEVELS),
  ...Object.values(PERMISSIONS.SUBJECTS),
  PERMISSIONS.COURSES.READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS.READ,
  PERMISSIONS.ACADEMIC_TRANSITIONS.READ,
  PERMISSIONS.ACADEMIC_TRANSITIONS.MANAGE,
  PERMISSIONS.ACADEMIC_EVALUATION.READ,
  PERMISSIONS.ACADEMIC_EVALUATION.MANAGE_PLATFORM_TEMPLATES,
  PERMISSIONS.ACADEMIC_PLANNING.READ,
  PERMISSIONS.CLASS_SESSIONS.READ,
  PERMISSIONS.ASSESSMENTS.READ,
  PERMISSIONS.GRADES.READ,
  PERMISSIONS.ATTENDANCE.READ,
  PERMISSIONS.ATTENDANCE.WRITE,
  PERMISSIONS.REPORT_CARDS.READ,
] as const satisfies readonly Permission[];

const ADMIN_INSTITUTION_PERMISSIONS = [
  PERMISSIONS.INSTITUTIONS.READ,
  PERMISSIONS.INSTITUTIONS.UPDATE_SETTINGS,
  PERMISSIONS.INSTITUTIONS.UPDATE_BRANDING,
  PERMISSIONS.INSTITUTIONS.UPLOAD_LOGO,
  PERMISSIONS.USERS.READ,
  PERMISSIONS.USERS.CREATE,
  PERMISSIONS.USERS.UPDATE,
  PERMISSIONS.USERS.DELETE,
  PERMISSIONS.INSTITUTION_MEMBERSHIPS.READ,
  PERMISSIONS.ACADEMIC_PERIODS.READ,
  PERMISSIONS.ACADEMIC_PERIODS.SELECT_CONTEXT,
  PERMISSIONS.ACADEMIC_LEVELS.READ,
  PERMISSIONS.GRADE_LEVELS.READ,
  PERMISSIONS.SUBJECTS.READ,
  ...Object.values(PERMISSIONS.COURSES),
  ...Object.values(PERMISSIONS.TEACHER_ASSIGNMENTS),
  ...Object.values(PERMISSIONS.STUDENTS),
  ...Object.values(PERMISSIONS.ENROLLMENTS),
  ...Object.values(PERMISSIONS.ACADEMIC_TRANSITIONS),
  PERMISSIONS.ACADEMIC_EVALUATION.READ,
  PERMISSIONS.ACADEMIC_EVALUATION.MANAGE,
  PERMISSIONS.ACADEMIC_PLANNING.READ,
  PERMISSIONS.CLASS_SESSIONS.READ,
  PERMISSIONS.ASSESSMENTS.READ,
  PERMISSIONS.GRADES.READ,
  PERMISSIONS.ACADEMIC_PERFORMANCE.READ,
  PERMISSIONS.REPORT_CARDS.READ,
  PERMISSIONS.ATTENDANCE.READ,
  PERMISSIONS.ATTENDANCE.WRITE,
  PERMISSIONS.ATTENDANCE_JUSTIFICATIONS.REVIEW,
] as const satisfies readonly Permission[];

const TEACHER_ASSIGNMENT_PERMISSIONS = [
  PERMISSIONS.ACADEMIC_PERIODS.READ,
  PERMISSIONS.ACADEMIC_PERIODS.SELECT_CONTEXT,
  PERMISSIONS.ACADEMIC_LEVELS.READ,
  PERMISSIONS.GRADE_LEVELS.READ,
  PERMISSIONS.SUBJECTS.READ,
  PERMISSIONS.COURSES.READ,
  PERMISSIONS.TEACHER_ASSIGNMENTS.READ,
  PERMISSIONS.STUDENTS.READ,
  PERMISSIONS.ENROLLMENTS.READ,
  PERMISSIONS.ACADEMIC_EVALUATION.READ,
  ...Object.values(PERMISSIONS.ACADEMIC_PLANNING),
  ...Object.values(PERMISSIONS.CLASS_SESSIONS),
  ...Object.values(PERMISSIONS.ASSESSMENTS),
  ...Object.values(PERMISSIONS.GRADES),
  PERMISSIONS.ACADEMIC_PERFORMANCE.READ,
  PERMISSIONS.REPORT_CARDS.READ,
  PERMISSIONS.ATTENDANCE.READ,
  PERMISSIONS.ATTENDANCE.WRITE,
] as const satisfies readonly Permission[];

const STUDENT_SELF_SERVICE_PERMISSIONS = [
  PERMISSIONS.ACADEMIC_PERIODS.READ,
  PERMISSIONS.ACADEMIC_PERIODS.SELECT_CONTEXT,
  PERMISSIONS.ACADEMIC_LEVELS.READ,
  PERMISSIONS.GRADE_LEVELS.READ,
  PERMISSIONS.SUBJECTS.READ,
  PERMISSIONS.STUDENTS.READ,
  PERMISSIONS.ENROLLMENTS.READ,
  PERMISSIONS.GRADES.READ,
  PERMISSIONS.ACADEMIC_PERFORMANCE.READ,
  PERMISSIONS.REPORT_CARDS.READ,
  PERMISSIONS.ATTENDANCE.READ,
  PERMISSIONS.ATTENDANCE_JUSTIFICATIONS.SUBMIT,
] as const satisfies readonly Permission[];

const REPRESENTATIVE_LINKED_PERMISSIONS = [
  // Current platform read routes include representatives, while resource access
  // remains constrained by relationship checks in services.
  PERMISSIONS.ACADEMIC_PERIODS.READ,
  PERMISSIONS.ACADEMIC_LEVELS.READ,
  PERMISSIONS.GRADE_LEVELS.READ,
  PERMISSIONS.SUBJECTS.READ,
  PERMISSIONS.ENROLLMENTS.READ,
  PERMISSIONS.GRADES.READ,
  PERMISSIONS.ACADEMIC_PERFORMANCE.READ,
  PERMISSIONS.REPORT_CARDS.READ,
  PERMISSIONS.ATTENDANCE.READ,
  PERMISSIONS.ATTENDANCE_JUSTIFICATIONS.SUBMIT,
  PERMISSIONS.REPRESENTATIVE_STUDENTS.READ,
] as const satisfies readonly Permission[];

/**
 * Maximum capabilities a role may receive in the future permission model.
 * Phase 1 does not assign these per user or use them for endpoint enforcement.
 */
export const ROLE_ALLOWED_PERMISSIONS: RolePermissionMap = Object.freeze({
  [Role.SUPER_ADMIN]: PLATFORM_CONFIGURATION_PERMISSIONS,
  [Role.ADMIN]: ADMIN_INSTITUTION_PERMISSIONS,
  [Role.TEACHER]: TEACHER_ASSIGNMENT_PERMISSIONS,
  [Role.STUDENT]: STUDENT_SELF_SERVICE_PERMISSIONS,
  [Role.REPRESENTATIVE]: REPRESENTATIVE_LINKED_PERMISSIONS,
});

/**
 * Current compatibility capabilities. Kept separate from allowed permissions so
 * profiles and membership grants can evolve without changing the role boundary.
 */
export const ROLE_BASELINE_PERMISSIONS: RolePermissionMap = Object.freeze({
  [Role.SUPER_ADMIN]: [...PLATFORM_CONFIGURATION_PERMISSIONS],
  [Role.ADMIN]: [...ADMIN_INSTITUTION_PERMISSIONS],
  [Role.TEACHER]: [...TEACHER_ASSIGNMENT_PERMISSIONS],
  [Role.STUDENT]: [...STUDENT_SELF_SERVICE_PERMISSIONS],
  [Role.REPRESENTATIVE]: [...REPRESENTATIVE_LINKED_PERMISSIONS],
});

export function assertRolePermissionCatalogIntegrity(): void {
  const catalog = new Set<Permission>(ALL_PERMISSIONS);

  if (catalog.size !== ALL_PERMISSIONS.length) {
    throw new Error('Permission catalog identifiers must be unique');
  }

  for (const role of Object.values(Role)) {
    const allowed = ROLE_ALLOWED_PERMISSIONS[role];
    const baseline = ROLE_BASELINE_PERMISSIONS[role];

    for (const permission of allowed) {
      if (!catalog.has(permission)) {
        throw new Error(
          `Role ${role} contains a permission outside the catalog`,
        );
      }
    }

    for (const permission of baseline) {
      if (!catalog.has(permission) || !allowed.includes(permission)) {
        throw new Error(
          `Role ${role} baseline permission must belong to its allowed catalog`,
        );
      }
    }
  }
}
