export const INSTITUTIONS_CONTEXT = 'InstitutionsService';

export const INSTITUTION_LOG_EVENTS = {
  CREATED: 'INSTITUTION_CREATED',
  UPDATED: 'INSTITUTION_UPDATED',
  DELETED: 'INSTITUTION_DELETED',
  ACTIVATED: 'INSTITUTION_ACTIVATED',
  DEACTIVATED: 'INSTITUTION_DEACTIVATED',
  SETTINGS_UPDATED: 'INSTITUTION_SETTINGS_UPDATED',
  BRANDING_UPDATED: 'INSTITUTION_BRANDING_UPDATED',
  LOGO_UPLOADED: 'INSTITUTION_LOGO_UPLOADED',
  VALIDATION_FAILED: 'INSTITUTION_VALIDATION_FAILED',
  OWNERSHIP_CONFLICT: 'INSTITUTION_OWNERSHIP_CONFLICT',
} as const;
