export const ACADEMIC_PERIOD_TRANSITIONS_CONTEXT =
  'AcademicPeriodTransitionsService';

export const TRANSITION_LOG_EVENTS = {
  PREVIEWED: 'ACADEMIC_TRANSITION_PREVIEWED',
  EXECUTED: 'ACADEMIC_TRANSITION_EXECUTED',
  FAILED: 'ACADEMIC_TRANSITION_FAILED',
  ACTIVE_PERIOD_SET: 'INSTITUTION_ACTIVE_PERIOD_SET',
  VALIDATION_FAILED: 'ACADEMIC_TRANSITION_VALIDATION_FAILED',
  AUTHORIZATION_FAILED: 'ACADEMIC_TRANSITION_AUTHORIZATION_FAILED',
} as const;
