export const INSTITUTION_MEMBERSHIPS_CONTEXT = 'InstitutionMembershipsService';

export const MEMBERSHIP_LOG_EVENTS = {
  ASSIGNED: 'INSTITUTION_MEMBERSHIP_ASSIGNED',
  UPDATED: 'INSTITUTION_MEMBERSHIP_UPDATED',
  REMOVED: 'INSTITUTION_MEMBERSHIP_REMOVED',
  ACTIVATED: 'INSTITUTION_MEMBERSHIP_ACTIVATED',
  DEACTIVATED: 'INSTITUTION_MEMBERSHIP_DEACTIVATED',
  VALIDATION_FAILED: 'INSTITUTION_MEMBERSHIP_VALIDATION_FAILED',
  AUTHORIZATION_FAILED: 'INSTITUTION_MEMBERSHIP_AUTHORIZATION_FAILED',
} as const;
